# Generated by Django 4.2.8 on 2023-12-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weave_manager', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
