# Generated by Django 5.0.1 on 2024-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weave_manager', '0002_rename_thread_comment_thread_commentvote_threadvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='votes',
        ),
    ]
