# Generated by Django 5.0.1 on 2024-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weave_manager', '0004_thread_votes_alter_commentvote_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
