# Generated by Django 5.0.1 on 2024-02-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weave_manager', '0005_comment_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
