# Generated by Django 5.0.1 on 2024-02-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weave_manager', '0006_alter_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='thread_pictures'),
        ),
    ]
